---
- name: Create brew tap
  command: "/usr/local/bin/brew tap-new {{ homebrew_tap_user }}/local-{{ item.name }}"
  args:
    creates: "/usr/local/Homebrew/Library/Taps/build/homebrew-local-{{ item.name }}/README.md"

- name: Brew extract
  command: "brew extract --version={{ item.version }} {{ item.name }} {{ homebrew_tap_user }}/local-{{ item.name }}"
  args:
    creates: "/usr/local/Homebrew/Library/Taps/{{ homebrew_tap_user }}/homebrew-local-{{ item.name }}/Formula/{{ item.name }}@{{ item.version }}.rb"

- name: Install package
  homebrew:
    name: "{{ item.name }}@{{ item.version }}"
    state: present
